### ISSUE TITLE
Add example for remoteproc

### ISSUE THREAD

**Issue by dinuxbg** [dinuxbg/pru-gcc-examples#2]
Try to write a pru-gcc example for the new PRU bridge, or write a simple standalone rpmsg example. This will probably require some trivial changes to the remoteproc driver in order to load the pru-gcc ELF variant.

**Comment by dinuxbg** [comment]
Remoteproc kernel driver must mask the IRAM address for PRU binutils ELF images to be loaded. See attached patch.
[0001-Fix-remoteproc-to-work-with-the-PRU-GNU-Binutils-por.txt](https://github.com/dinuxbg/pru-gcc-examples/files/11379/0001-Fix-remoteproc-to-work-with-the-PRU-GNU-Binutils-por.txt)

**Comment by jadonk** [comment]
Can you send a pull request for the patch?

**Comment by jadonk** [comment]
Oh, wait, I thought this was against the TI examples. Nevermind. Thanks again for advancing this project!! We need to try to get this into RobertCNelson's package feeds.

**Comment by dinuxbg** [comment]
Added example and step-by-step instructions with commit 825ee2f5d84e1675bd9e51420c81eebcea992be5

**Comment by dinuxbg** [comment]
Thanks Jason. I created a pull request here: https://github.com/beagleboard/linux/pull/47  . I hope this is the correct github project.

**Comment by RobertCNelson** [comment]
Thanks @dinuxbg all merged up in v4.1.x/v4.1.x-rt branches... I just pushed a build a couple hours ago for dsp/c6000 support on the x15, so the worst case this will get tagged/pushed as r24 next thursday..

**Comment by dinuxbg** [comment]
Thank you for merging the fix. I'll make sure to use the correct github project next time.

**Comment by RobertCNelson** [comment]
@dinuxbg that one is perfectly fine and the reason it's their for users/developers.  I then 'git am' the patch into a overly complex build/merge/patch script system. (things are based on two moving targets, ti.com/git/ and kernel.org stable's tree..)
Regards,

**Comment by dinuxbg** [comment]
Tested with bone-debian-8.2-console-armhf-2015-10-25-2gb.img
