### ISSUE TITLE
hc-sr04-range-sensor: How to read data from a Beaglebone Black

### ISSUE THREAD

**Issue by rogerlucas** [dinuxbg/pru-gcc-examples#3]
Hello,

Can you give me some help to use this example on a Beaglebone Black?

I can run the firmware, but I'm lost on how to read the read data from the hc-sr04-range-sensor example.

**Comment by dinuxbg** [comment]
Hi. Commands are given at the end of README.md. If you can run the firmware, and your wiring is correct, then you can type the following commands to see the measurement in millimeters:

> ```
> sudo bash
> echo hello > /dev/rpmsg_pru31
> cat /dev/rpmsg_pru31 
> ```
> Press Ctrl+C to exit
