### ISSUE TITLE
Is this step still necessary ?

### ISSUE THREAD

**Issue by VedantParanjape** [dinuxbg/pru-gcc-examples#7]
https://github.com/dinuxbg/pru-gcc-examples/blob/master/REMOTEPROC.md Do I still need to do this ?

Running on a pocketbeagle

```
Linux beaglebone 4.19.94-ti-r45 #1buster SMP PREEMPT Thu Jun 18 19:18:41 UTC 2020 armv7l GNU/Linux
```

**Comment by dinuxbg** [comment]
No, it is no longer needed. Remoteproc driver should be enabled and patched for pru-gcc in recent Beagleboard Debian images.

As a side note, I wish TI would mainline PRU remoteproc soon. This would avoid so much confusion in the Beagleboard community.
